export const GET_PAGES_START = 'GET_PAGES_START';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';
export const GET_PAGES_FAILED = 'GET_PAGES_FAILED';

export const DELETE_PAGE_START = 'DELETE_PAGE_START';
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS';
export const DELETE_PAGE_FAILED = 'DELETE_PAGE_FAILED';

export const GET_PAGE_START = 'GET_PAGE_START';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
export const GET_PAGE_FAILED = 'GET_PAGE_FAILED';

export const ADD_PAGE_START = 'ADD_PAGE_START';
export const ADD_PAGE_SUCCESS = 'ADD_PAGE_SUCCESS';
export const ADD_PAGE_FAILED = 'ADD_PAGE_FAILED';

export const EDIT_PAGE_START = 'EDIT_PAGE_START';
export const EDIT_PAGE_SUBMIT = 'EDIT_PAGE_SUBMIT';
export const EDIT_PAGE_SUCCESS = 'EDIT_PAGE_SUCCESS';
export const EDIT_PAGE_FAILED = 'EDIT_PAGE_FAILED';

export const RESET = 'RESET';
